version: "3.8"

services:
  jotter:
    build: .
    ports:
      - "8000:8000"
    environment:
      - JOT_HOST=0.0.0.0
      - JOT_PORT=8000
      - JOT_DIR=/app/jots
    volumes:
      - ${JOTS_DIR:-./jots}:/app/jots
    restart: unless-stopped
