version: "3"

tasks:
  build:
    desc: Build the Jotter binary
    vars:
      BUILD_DIR: '{{.BUILD_DIR | default "build"}}'
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - go build -o {{.BUILD_DIR}}/jotter cmd/jotter/main.go
      - |
        echo "Build completed successfully!"
        echo "Binary: {{.BUILD_DIR}}/jotter"

  test:
    desc: Run all tests
    cmds:
      - go test ./...

  test-single:
    desc: Run a single test (specify TEST_NAME variable)
    vars:
      TEST_NAME: '{{.TEST_NAME | default "TestExample"}}'
    cmds:
      - go test -run ^{{.TEST_NAME}}$ ./cmd/jotter

  bench:
    desc: Run benchmarks
    cmds:
      - go test -bench . ./cmd/jotter

  lint:
    desc: Run Go vet linter
    cmds:
      - go vet ./...

  fmt:
    desc: Format Go code
    cmds:
      - gofmt -w .
      - echo "Code formatted successfully!"

  gen-certs:
    desc: Generate self-signed TLS certificates for development
    vars:
      DOMAIN: '{{.DOMAIN | default "localhost"}}'
      BUILD_DIR: '{{.BUILD_DIR | default "build"}}'
      CERT_DIR: "{{.BUILD_DIR}}/certs"
      CERT_FILE: "{{.BUILD_DIR}}/certs/server.crt"
      KEY_FILE: "{{.BUILD_DIR}}/certs/server.key"
    cmds:
      - mkdir -p {{.CERT_DIR}}
      - |
        echo "Generating self-signed TLS certificate for domain: {{.DOMAIN}}"
        openssl genrsa -out {{.KEY_FILE}} 2048
        openssl req -new -x509 -key {{.KEY_FILE}} -out {{.CERT_FILE}} -days 365 \
          -subj "/C=US/ST=State/L=City/O=Organization/CN={{.DOMAIN}}" \
          -addext "subjectAltName=DNS:{{.DOMAIN}},DNS:localhost,IP:127.0.0.1"
        echo "Certificate generated successfully!"
        echo "Certificate: {{.CERT_FILE}}"
        echo "Private Key: {{.KEY_FILE}}"
        echo ""
        echo "To run Jotter with TLS, set these environment variables:"
        echo "export JOT_CERT_FILE=$(pwd)/{{.CERT_FILE}}"
        echo "export JOT_KEY_FILE=$(pwd)/{{.KEY_FILE}}"

  dev:
    desc: Run development server with auto-reload and TLS
    deps: [tools, gen-certs]
    vars:
      BUILD_DIR: '{{.BUILD_DIR | default "build"}}'
    env:
      JOT_HOST: localhost
      JOT_PORT: 8443
      JOT_DIR: jots
      JOT_CERT_FILE: "{{.BUILD_DIR}}/certs/server.crt"
      JOT_KEY_FILE: "{{.BUILD_DIR}}/certs/server.key"
    cmds:
      - |
        # Determine URL, appending token if one exists
        URL="https://localhost:8443"
        JOT_FILE=$(find jots -name "jot_*.txt" -print -quit)
        if [ -n "$JOT_FILE" ]; then
          TOKEN=$(basename "$JOT_FILE" .txt | sed 's/^jot_//')
          URL="$URL?token=$TOKEN"
        fi

        echo "Starting Jotter development server with auto-reload and TLS..."
        echo "Server will be available at: $URL"
        echo "Note: You may need to accept the self-signed certificate warning in your browser"
        echo "Auto-reload is enabled - the server will restart when Go files change"

        # Start the server in the background
        air &
        SERVER_PID=$!

        # Wait a moment for the server to start
        sleep 2

        # Open browser if CHROME_BIN is set
        if [ -n "$CHROME_BIN" ]; then
          echo "Opening browser at $URL"
          "$CHROME_BIN" "$URL" 2>/dev/null &
        else
          echo "Set CHROME_BIN environment variable to automatically open browser"
        fi

        # Wait for the server process
        wait $SERVER_PID

  build-docker:
    desc: Build Docker image for Jotter
    vars:
      IMAGE_NAME: '{{.IMAGE_NAME | default "jotter"}}'
      TAG: '{{.TAG | default "latest"}}'
    cmds:
      - docker build -t {{.IMAGE_NAME}}:{{.TAG}} .
      - |
        echo "Docker image built successfully: {{.IMAGE_NAME}}:{{.TAG}}"
        echo ""
        echo "To run with HTTP:"
        echo "docker run -d -p 8000:8000 -v /path/to/jots:/app/jots {{.IMAGE_NAME}}:{{.TAG}}"
        echo ""
        echo "To run with TLS (generate certificates first with 'task gen-certs'):"
        echo "docker run -d -p 8443:8000 \\"
        echo "  -v $(pwd)/certs:/app/certs \\"
        echo "  -e JOT_CERT_FILE=/app/certs/server.crt \\"
        echo "  -e JOT_KEY_FILE=/app/certs/server.key \\"
        echo "  -v /path/to/jots:/app/jots \\"
        echo "  {{.IMAGE_NAME}}:{{.TAG}}"

  tools:
    desc: Install necessary development tools
    cmds:
      - go install github.com/air-verse/air@latest
      - echo "Installed air successfully!"
